# permissions for end users to edit firewalls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: firewall-editor-role
rules:
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - firewalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.tutorial.kubebuilder.io
  resources:
  - firewalls/status
  verbs:
  - get
